#ifndef INC_LCD_TILESET_H_
#define INC_LCD_TILESET_H_

#include <stdint.h>

#define TILESET_COLOR_COUNT 5
#define TILESET_TILE_COUNT  128
#define TILESET_TILE_SIZE   (8 * 8)

extern const uint16_t TILESET[TILESET_COLOR_COUNT][TILESET_TILE_COUNT][TILESET_TILE_SIZE];

#endif /* INC_LCD_TILESET_H_ */
